spring:
  application:
    name: wellb-api

  # --- 데이터소스 및 JPA 설정 (기존 내용 유지) ---
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    # 프로젝트의 기본 패키지에 대해 DEBUG 레벨로 설정하여 상세한 로그를 확인합니다.
    # 서비스나 컨트롤러에서 log.debug("...")로 남긴 로그가 모두 출력됩니다.
    kr.co.misoinfo: DEBUG

    # Spring 프레임워크 자체의 로그는 너무 많을 수 있으므로 INFO 레벨로 유지합니다.
    org.springframework.web: INFO
    org.hibernate: INFO # JPA의 show-sql과 별개로 Hibernate 내부 동작 로그